-- Rename every table to snake_case plural (models keep their PascalCase
-- names in Prisma code via @@map). RENAME keeps all existing rows.

ALTER TABLE "User" RENAME TO "users";
ALTER TABLE "Role" RENAME TO "roles";
ALTER TABLE "RolePermission" RENAME TO "role_permissions";
ALTER TABLE "Branch" RENAME TO "branches";
ALTER TABLE "PdLifeApplication" RENAME TO "pd_life_applications";
ALTER TABLE "PdLifeBeneficiary" RENAME TO "pd_life_beneficiaries";
ALTER TABLE "PdLifeIpeakRequest" RENAME TO "pd_life_ipeak_requests";
ALTER TABLE "PdLifePolicyNumberSequence" RENAME TO "pd_life_policy_number_sequences";
ALTER TABLE "OfwApplication" RENAME TO "ofw_applications";
ALTER TABLE "OfwBeneficiary" RENAME TO "ofw_beneficiaries";
ALTER TABLE "CtplApplication" RENAME TO "ctpl_applications";
ALTER TABLE "GtpApplication" RENAME TO "gtp_applications";
ALTER TABLE "LifePaymentTransaction" RENAME TO "life_payment_transactions";
ALTER TABLE "NonLifePaymentTransaction" RENAME TO "non_life_payment_transactions";
ALTER TABLE "GeneratedDocument" RENAME TO "generated_documents";
ALTER TABLE "Endorsement" RENAME TO "endorsements";
ALTER TABLE "NumberSequence" RENAME TO "number_sequences";
ALTER TABLE "AuditLog" RENAME TO "audit_logs";

ALTER INDEX "User_email_key" RENAME TO "users_email_key";
ALTER INDEX "User_roleId_idx" RENAME TO "users_roleId_idx";
ALTER INDEX "User_branchId_idx" RENAME TO "users_branchId_idx";
ALTER INDEX "Role_name_productScope_key" RENAME TO "roles_name_productScope_key";
ALTER INDEX "RolePermission_roleId_moduleName_key" RENAME TO "role_permissions_roleId_moduleName_key";
ALTER INDEX "PdLifeApplication_policyNumber_key" RENAME TO "pd_life_applications_policyNumber_key";
ALTER INDEX "PdLifeApplication_status_idx" RENAME TO "pd_life_applications_status_idx";
ALTER INDEX "PdLifeApplication_planCategory_idx" RENAME TO "pd_life_applications_planCategory_idx";
ALTER INDEX "PdLifeBeneficiary_applicationId_idx" RENAME TO "pd_life_beneficiaries_applicationId_idx";
ALTER INDEX "PdLifeIpeakRequest_applicationId_idx" RENAME TO "pd_life_ipeak_requests_applicationId_idx";
ALTER INDEX "PdLifeIpeakRequest_policyNumber_idx" RENAME TO "pd_life_ipeak_requests_policyNumber_idx";
ALTER INDEX "OfwApplication_referenceNo_key" RENAME TO "ofw_applications_referenceNo_key";
ALTER INDEX "OfwApplication_policyNumber_key" RENAME TO "ofw_applications_policyNumber_key";
ALTER INDEX "OfwApplication_status_idx" RENAME TO "ofw_applications_status_idx";
ALTER INDEX "OfwBeneficiary_applicationId_idx" RENAME TO "ofw_beneficiaries_applicationId_idx";
ALTER INDEX "CtplApplication_policyNumber_key" RENAME TO "ctpl_applications_policyNumber_key";
ALTER INDEX "CtplApplication_referenceNo_key" RENAME TO "ctpl_applications_referenceNo_key";
ALTER INDEX "CtplApplication_status_idx" RENAME TO "ctpl_applications_status_idx";
ALTER INDEX "GtpApplication_policyNumber_key" RENAME TO "gtp_applications_policyNumber_key";
ALTER INDEX "GtpApplication_referenceNo_key" RENAME TO "gtp_applications_referenceNo_key";
ALTER INDEX "GtpApplication_status_idx" RENAME TO "gtp_applications_status_idx";
ALTER INDEX "LifePaymentTransaction_policyNo_key" RENAME TO "life_payment_transactions_policyNo_key";
ALTER INDEX "NonLifePaymentTransaction_product_idx" RENAME TO "non_life_payment_transactions_product_idx";
ALTER INDEX "NonLifePaymentTransaction_policyNumber_idx" RENAME TO "non_life_payment_transactions_policyNumber_idx";
ALTER INDEX "NonLifePaymentTransaction_referenceNo_idx" RENAME TO "non_life_payment_transactions_referenceNo_idx";
ALTER INDEX "GeneratedDocument_s3Key_key" RENAME TO "generated_documents_s3Key_key";
ALTER INDEX "GeneratedDocument_invoiceNumber_key" RENAME TO "generated_documents_invoiceNumber_key";
ALTER INDEX "GeneratedDocument_applicationType_applicationId_idx" RENAME TO "generated_documents_applicationType_applicationId_idx";
ALTER INDEX "GeneratedDocument_endorsementId_idx" RENAME TO "generated_documents_endorsementId_idx";
ALTER INDEX "Endorsement_endorsementNumber_key" RENAME TO "endorsements_endorsementNumber_key";
ALTER INDEX "Endorsement_invoiceNumber_key" RENAME TO "endorsements_invoiceNumber_key";
ALTER INDEX "Endorsement_creditMemoNumber_key" RENAME TO "endorsements_creditMemoNumber_key";
ALTER INDEX "Endorsement_product_status_idx" RENAME TO "endorsements_product_status_idx";
ALTER INDEX "Endorsement_ctplApplicationId_idx" RENAME TO "endorsements_ctplApplicationId_idx";
ALTER INDEX "Endorsement_ofwApplicationId_idx" RENAME TO "endorsements_ofwApplicationId_idx";
ALTER INDEX "Endorsement_gtpApplicationId_idx" RENAME TO "endorsements_gtpApplicationId_idx";
ALTER INDEX "AuditLog_userId_idx" RENAME TO "audit_logs_userId_idx";
ALTER INDEX "AuditLog_module_idx" RENAME TO "audit_logs_module_idx";

ALTER TABLE "users" RENAME CONSTRAINT "User_roleId_fkey" TO "users_roleId_fkey";
ALTER TABLE "users" RENAME CONSTRAINT "User_branchId_fkey" TO "users_branchId_fkey";
ALTER TABLE "role_permissions" RENAME CONSTRAINT "RolePermission_roleId_fkey" TO "role_permissions_roleId_fkey";
ALTER TABLE "pd_life_beneficiaries" RENAME CONSTRAINT "PdLifeBeneficiary_applicationId_fkey" TO "pd_life_beneficiaries_applicationId_fkey";
ALTER TABLE "pd_life_ipeak_requests" RENAME CONSTRAINT "PdLifeIpeakRequest_applicationId_fkey" TO "pd_life_ipeak_requests_applicationId_fkey";
ALTER TABLE "ofw_beneficiaries" RENAME CONSTRAINT "OfwBeneficiary_applicationId_fkey" TO "ofw_beneficiaries_applicationId_fkey";
ALTER TABLE "life_payment_transactions" RENAME CONSTRAINT "LifePaymentTransaction_policyNo_fkey" TO "life_payment_transactions_policyNo_fkey";
ALTER TABLE "non_life_payment_transactions" RENAME CONSTRAINT "NonLifePaymentTransaction_ctplApplicationId_fkey" TO "non_life_payment_transactions_ctplApplicationId_fkey";
ALTER TABLE "non_life_payment_transactions" RENAME CONSTRAINT "NonLifePaymentTransaction_ofwApplicationId_fkey" TO "non_life_payment_transactions_ofwApplicationId_fkey";
ALTER TABLE "non_life_payment_transactions" RENAME CONSTRAINT "NonLifePaymentTransaction_gtpApplicationId_fkey" TO "non_life_payment_transactions_gtpApplicationId_fkey";
ALTER TABLE "generated_documents" RENAME CONSTRAINT "GeneratedDocument_endorsementId_fkey" TO "generated_documents_endorsementId_fkey";
ALTER TABLE "endorsements" RENAME CONSTRAINT "Endorsement_ctplApplicationId_fkey" TO "endorsements_ctplApplicationId_fkey";
ALTER TABLE "endorsements" RENAME CONSTRAINT "Endorsement_ofwApplicationId_fkey" TO "endorsements_ofwApplicationId_fkey";
ALTER TABLE "endorsements" RENAME CONSTRAINT "Endorsement_gtpApplicationId_fkey" TO "endorsements_gtpApplicationId_fkey";
ALTER TABLE "audit_logs" RENAME CONSTRAINT "AuditLog_userId_fkey" TO "audit_logs_userId_fkey";
ALTER TABLE "users" RENAME CONSTRAINT "User_pkey" TO "users_pkey";
ALTER TABLE "roles" RENAME CONSTRAINT "Role_pkey" TO "roles_pkey";
ALTER TABLE "role_permissions" RENAME CONSTRAINT "RolePermission_pkey" TO "role_permissions_pkey";
ALTER TABLE "branches" RENAME CONSTRAINT "Branch_pkey" TO "branches_pkey";
ALTER TABLE "pd_life_applications" RENAME CONSTRAINT "PdLifeApplication_pkey" TO "pd_life_applications_pkey";
ALTER TABLE "pd_life_beneficiaries" RENAME CONSTRAINT "PdLifeBeneficiary_pkey" TO "pd_life_beneficiaries_pkey";
ALTER TABLE "pd_life_ipeak_requests" RENAME CONSTRAINT "PdLifeIpeakRequest_pkey" TO "pd_life_ipeak_requests_pkey";
ALTER TABLE "pd_life_policy_number_sequences" RENAME CONSTRAINT "PdLifePolicyNumberSequence_pkey" TO "pd_life_policy_number_sequences_pkey";
ALTER TABLE "ofw_applications" RENAME CONSTRAINT "OfwApplication_pkey" TO "ofw_applications_pkey";
ALTER TABLE "ofw_beneficiaries" RENAME CONSTRAINT "OfwBeneficiary_pkey" TO "ofw_beneficiaries_pkey";
ALTER TABLE "ctpl_applications" RENAME CONSTRAINT "CtplApplication_pkey" TO "ctpl_applications_pkey";
ALTER TABLE "gtp_applications" RENAME CONSTRAINT "GtpApplication_pkey" TO "gtp_applications_pkey";
ALTER TABLE "life_payment_transactions" RENAME CONSTRAINT "LifePaymentTransaction_pkey" TO "life_payment_transactions_pkey";
ALTER TABLE "non_life_payment_transactions" RENAME CONSTRAINT "NonLifePaymentTransaction_pkey" TO "non_life_payment_transactions_pkey";
ALTER TABLE "generated_documents" RENAME CONSTRAINT "GeneratedDocument_pkey" TO "generated_documents_pkey";
ALTER TABLE "endorsements" RENAME CONSTRAINT "Endorsement_pkey" TO "endorsements_pkey";
ALTER TABLE "number_sequences" RENAME CONSTRAINT "NumberSequence_pkey" TO "number_sequences_pkey";
ALTER TABLE "audit_logs" RENAME CONSTRAINT "AuditLog_pkey" TO "audit_logs_pkey";
