// Standalone seed script - run with `npx tsx prisma/seed.ts` (or `npm run seed`).
// Uses PrismaClient directly rather than importing src/lib/prisma so this file
// stays runnable outside the compiled app.
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  // --- Role -----------------------------------------------------------
  const role = await prisma.role.upsert({
    where: { name_productScope: { name: 'Operations', productScope: 'PD Life' } },
    update: {},
    create: {
      name: 'Operations',
      productScope: 'PD Life',
      isDirectMarketing: true,
      permissions: {
        create: [
          { moduleName: 'Application Screening', canRead: true, canWrite: true, canDelete: false },
          { moduleName: 'Application Inquiry', canRead: true, canWrite: false, canDelete: false },
          { moduleName: 'Payment Transactions', canRead: true, canWrite: true, canDelete: false },
          { moduleName: 'Branch Directory', canRead: true, canWrite: false, canDelete: false },
        ],
      },
    },
  });

  // --- Branch -----------------------------------------------------------
  const existingBranch = await prisma.branch.findFirst({ where: { city: 'Makati City', division: 'LIFE' } });
  const branch =
    existingBranch ??
    (await prisma.branch.create({
      data: {
        division: 'LIFE',
        region: 'NCR',
        province: 'Metro Manila',
        city: 'Makati City',
        address: '7th Floor, Paramount Building, Ayala Avenue',
        barangay: 'Bel-Air',
        zipcode: '1226',
        mobile: '+639171234567',
        telephone: '(02) 8888-1234',
        fax: '(02) 8888-1235',
        email: 'makati.branch@paramount.com.ph',
        website: 'https://www.paramountdirect.com.ph',
        status: 'Active',
      },
    }));

  // --- Admin user -----------------------------------------------------------
  const passwordHash = await bcrypt.hash('admin123', 10);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@paramount.com.ph' },
    update: {
      firstName: 'Juan',
      lastName: 'Dela Cruz',
      passwordHash,
      assignedProducts: ['PD Life', 'OFW', 'CTPL', 'GTP'],
      roleId: role.id,
      branchId: branch.id,
      status: 'Active',
    },
    create: {
      email: 'admin@paramount.com.ph',
      firstName: 'Juan',
      lastName: 'Dela Cruz',
      passwordHash,
      assignedProducts: ['PD Life', 'OFW', 'CTPL', 'GTP'],
      roleId: role.id,
      branchId: branch.id,
      status: 'Active',
    },
  });

  // --- Sample data: safe to re-run, so clear each table first -----------
  await prisma.pdLifeApplication.deleteMany();
  await prisma.ofwApplication.deleteMany();
  await prisma.ctplApplication.deleteMany();
  await prisma.gtpApplication.deleteMany();

  await prisma.pdLifeApplication.createMany({
    data: [
      {
        payor: 'Maria Santos',
        planCategory: 'Health',
        planCode: 'HC-100',
        planDesc: 'HealthCare Plus 100',
        premium: '2500.00',
        source: 'Walk-in',
        dateReceived: new Date('2026-08-01'),
        status: 'Received',
        details: { applicantName: 'Maria Santos', age: 34, beneficiary: 'Jose Santos' },
      },
      {
        payor: 'Ramon Cruz',
        planCategory: 'LifeAccident',
        planCode: 'LA-200',
        planDesc: 'Life & Accident Shield 200',
        premium: '3800.00',
        source: 'Agent',
        dateReceived: new Date('2026-08-05'),
        dateScreened: new Date('2026-08-06'),
        screenedBy: 'Juan Dela Cruz',
        status: 'For_Verification',
        details: { applicantName: 'Ramon Cruz', age: 41, occupation: 'Engineer' },
      },
      {
        payor: 'Liza Reyes',
        planCategory: 'Comprehensive',
        planCode: 'CP-300',
        planDesc: 'Comprehensive Life Plan 300',
        premium: '5200.00',
        source: 'Online',
        dateReceived: new Date('2026-08-10'),
        status: 'For_Evaluation',
        details: { applicantName: 'Liza Reyes', age: 29, medicalHistory: 'None' },
      },
      {
        payor: 'Alfredo Villanueva',
        planCategory: 'Health',
        planCode: 'HC-150',
        planDesc: 'HealthCare Plus 150',
        premium: '3100.00',
        source: 'Broker',
        dateReceived: new Date('2026-08-12'),
        status: 'Paid',
        details: { applicantName: 'Alfredo Villanueva', age: 55 },
      },
      {
        payor: 'Grace Manalo',
        planCategory: 'LifeAccident',
        planCode: 'LA-250',
        planDesc: 'Life & Accident Shield 250',
        premium: '4400.00',
        source: 'Walk-in',
        dateReceived: new Date('2026-08-14'),
        status: 'Issued',
        details: { applicantName: 'Grace Manalo', age: 38 },
      },
    ],
  });

  await prisma.ofwApplication.createMany({
    data: [
      {
        lastName: 'Bautista',
        firstName: 'Rosalinda',
        middleName: 'Garcia',
        gender: 'Female',
        civilStatus: 'Married',
        birthdate: new Date('1985-03-12'),
        placeOfBirth: 'Cebu City',
        phAddress: '123 Mabini St., Cebu City',
        phCity: 'Cebu City',
        phone: '+639171112222',
        email: 'rosalinda.bautista@example.com',
        referralSource: 'Agency',
        natureOfEmployment: 'Direct_hired',
        coverageType: 'Land_based',
        occupation: 'Domestic Helper',
        passportNumber: 'P1234567',
        salaryAmount: 25000,
        salaryCurrency: 'HKD',
        employerName: 'Chan Family',
        employerCountry: 'Hong Kong',
        contractStart: new Date('2026-09-01'),
        contractEnd: new Date('2028-09-01'),
        insuranceStart: new Date('2026-09-01'),
        isConflictZone: false,
        passportDoc: 'Uploaded',
        visaDoc: 'Uploaded',
        employmentContractDoc: 'Uploaded',
        medicalCertificateDoc: 'Missing',
        premium: '1800.00',
        dateReceived: new Date('2026-08-15'),
        status: 'Received',
      },
      {
        lastName: 'Fernandez',
        firstName: 'Michael',
        middleName: 'Torres',
        gender: 'Male',
        civilStatus: 'Single',
        birthdate: new Date('1990-07-22'),
        placeOfBirth: 'Davao City',
        phAddress: '45 Rizal Ave., Davao City',
        phCity: 'Davao City',
        phone: '+639182223333',
        email: 'michael.fernandez@example.com',
        referralSource: 'Referral',
        natureOfEmployment: 'Balik_Manggagawa',
        coverageType: 'Sea_based',
        occupation: 'Able Seaman',
        passportNumber: 'P7654321',
        salaryAmount: 1200,
        salaryCurrency: 'USD',
        employerName: 'Ocean Star Shipping',
        employerCountry: 'Panama',
        contractStart: new Date('2026-09-10'),
        contractEnd: new Date('2027-09-10'),
        insuranceStart: new Date('2026-09-10'),
        isConflictZone: false,
        passportDoc: 'Uploaded',
        visaDoc: 'Missing',
        employmentContractDoc: 'Uploaded',
        medicalCertificateDoc: 'Uploaded',
        premium: '2200.00',
        dateReceived: new Date('2026-08-18'),
        status: 'Received',
      },
      {
        lastName: 'Lopez',
        firstName: 'Angelica',
        middleName: 'Dizon',
        gender: 'Female',
        civilStatus: 'Widower',
        birthdate: new Date('1978-11-05'),
        placeOfBirth: 'Iloilo City',
        phAddress: '78 Luna St., Iloilo City',
        phCity: 'Iloilo City',
        phone: '+639193334444',
        email: 'angelica.lopez@example.com',
        referralSource: 'Walk-in',
        natureOfEmployment: 'Direct_hired',
        coverageType: 'Land_based',
        occupation: 'Caregiver',
        passportNumber: 'P2233445',
        salaryAmount: 15000,
        salaryCurrency: 'PHP',
        employerName: 'Al Rashid Household',
        employerCountry: 'Saudi Arabia',
        contractStart: new Date('2026-07-01'),
        contractEnd: new Date('2028-07-01'),
        insuranceStart: new Date('2026-07-01'),
        isConflictZone: true,
        passportDoc: 'Uploaded',
        visaDoc: 'Uploaded',
        employmentContractDoc: 'Missing',
        medicalCertificateDoc: 'Missing',
        premium: '2600.00',
        dateReceived: new Date('2026-07-20'),
        status: 'Cancelled',
      },
      {
        lastName: 'Ramos',
        firstName: 'Bryan',
        middleName: 'Quiambao',
        gender: 'Male',
        civilStatus: 'Married',
        birthdate: new Date('1988-01-30'),
        placeOfBirth: 'Baguio City',
        phAddress: '12 Session Rd., Baguio City',
        phCity: 'Baguio City',
        phone: '+639204445555',
        email: 'bryan.ramos@example.com',
        referralSource: 'Agency',
        natureOfEmployment: 'Balik_Manggagawa',
        coverageType: 'Land_based',
        occupation: 'Construction Worker',
        passportNumber: 'P3344556',
        salaryAmount: 3000,
        salaryCurrency: 'Others',
        employerName: 'Gulf Builders LLC',
        employerCountry: 'Qatar',
        contractStart: new Date('2026-08-01'),
        contractEnd: new Date('2028-08-01'),
        insuranceStart: new Date('2026-08-01'),
        isConflictZone: false,
        passportDoc: 'Uploaded',
        visaDoc: 'Uploaded',
        employmentContractDoc: 'Uploaded',
        medicalCertificateDoc: 'Uploaded',
        premium: '1900.00',
        dateReceived: new Date('2026-08-22'),
        status: 'Duplicate',
      },
    ],
  });

  await prisma.ctplApplication.createMany({
    data: [
      {
        policyType: 'Private_Car',
        mvType: 'Sedan',
        renewalType: 'New_1_Year',
        clientType: 'Individual',
        ownerFirstName: 'Carlos',
        ownerMiddleName: 'Santos',
        ownerSurname: 'Mendoza',
        sameAsOwner: true,
        applicantFirstName: 'Carlos',
        applicantSurname: 'Mendoza',
        email: 'carlos.mendoza@example.com',
        mobileNumber: '+639171234567',
        plateNumber: 'ABC1234',
        mvFileNumber: 'MVF-00123',
        chassisNumber: 'CHS-99887766',
        requiresCOV: false,
        premium: '650.00',
        dateReceived: new Date('2026-08-02'),
        status: 'Completed',
      },
      {
        policyType: 'Motorcycle',
        mvType: 'Scooter',
        renewalType: 'Renewal',
        clientType: 'Individual',
        ownerFirstName: 'Ella',
        ownerMiddleName: 'Marasigan',
        ownerSurname: 'Tan',
        sameAsOwner: true,
        applicantFirstName: 'Ella',
        applicantSurname: 'Tan',
        email: 'ella.tan@example.com',
        mobileNumber: '+639182345678',
        plateNumber: 'MC5678',
        mvFileNumber: 'MVF-00456',
        chassisNumber: 'CHS-11223344',
        requiresCOV: false,
        premium: '260.00',
        dateReceived: new Date('2026-08-06'),
        status: 'Completed',
      },
      {
        policyType: 'Commercial_Vehicle',
        mvType: 'Delivery Van',
        renewalType: 'New_1_Year',
        clientType: 'Corporate_with_assignee',
        ownerFirstName: 'N/A',
        ownerMiddleName: 'N/A',
        ownerSurname: 'Swift Logistics Corp.',
        sameAsOwner: false,
        applicantFirstName: 'Patricia',
        applicantSurname: 'Uy',
        email: 'patricia.uy@swiftlogistics.example.com',
        mobileNumber: '+639193456789',
        plateNumber: 'CV9012',
        mvFileNumber: 'MVF-00789',
        chassisNumber: 'CHS-55667788',
        requiresCOV: true,
        premium: '1200.00',
        dateReceived: new Date('2026-08-11'),
        status: 'Reversed',
      },
      {
        policyType: 'Private_Car',
        mvType: 'SUV',
        renewalType: 'Renewal',
        clientType: 'Individual',
        ownerFirstName: 'Noel',
        ownerMiddleName: 'Aguilar',
        ownerSurname: 'Pascual',
        sameAsOwner: true,
        applicantFirstName: 'Noel',
        applicantSurname: 'Pascual',
        email: 'noel.pascual@example.com',
        mobileNumber: '+639204567890',
        plateNumber: 'SUV3456',
        mvFileNumber: 'MVF-01011',
        chassisNumber: 'CHS-22334455',
        requiresCOV: false,
        premium: '650.00',
        dateReceived: new Date('2026-08-19'),
        status: 'Spoiled',
      },
    ],
  });

  await prisma.gtpApplication.createMany({
    data: [
      {
        travelType: 'International',
        destinations: ['Japan', 'South Korea'],
        departureDate: new Date('2026-10-01'),
        returnDate: new Date('2026-10-10'),
        daysOfTravel: 9,
        applicationType: 'Individual',
        travelerFirstName: 'Andrea',
        travelerSurname: 'Villegas',
        birthdate: new Date('1995-05-14'),
        email: 'andrea.villegas@example.com',
        mobileNumber: '+639171112233',
        planVariant: 'Single_Trip',
        cruiseCoverage: false,
        hazardousSportsCoverage: false,
        isSchengenDestination: false,
        premium: '1500.00',
        dateReceived: new Date('2026-09-01'),
        status: 'Received',
      },
      {
        travelType: 'International',
        destinations: ['France', 'Italy', 'Spain'],
        departureDate: new Date('2026-11-05'),
        returnDate: new Date('2026-11-20'),
        daysOfTravel: 15,
        applicationType: 'Family',
        travelerFirstName: 'Michael',
        travelerSurname: 'Ong',
        birthdate: new Date('1982-02-19'),
        email: 'michael.ong@example.com',
        mobileNumber: '+639182223344',
        planVariant: 'Multi_Trip_90',
        cruiseCoverage: false,
        hazardousSportsCoverage: false,
        isSchengenDestination: true,
        premium: '4200.00',
        dateReceived: new Date('2026-09-03'),
        status: 'Received',
      },
      {
        travelType: 'Domestic',
        destinations: ['Palawan'],
        departureDate: new Date('2026-09-20'),
        returnDate: new Date('2026-09-25'),
        daysOfTravel: 5,
        applicationType: 'Individual',
        travelerFirstName: 'Sofia',
        travelerSurname: 'Domingo',
        birthdate: new Date('1999-09-09'),
        email: 'sofia.domingo@example.com',
        mobileNumber: '+639193334455',
        planVariant: 'Single_Trip',
        cruiseCoverage: false,
        hazardousSportsCoverage: true,
        isSchengenDestination: false,
        premium: '600.00',
        dateReceived: new Date('2026-09-05'),
        status: 'Duplicate',
      },
      {
        travelType: 'International',
        destinations: ['Australia'],
        departureDate: new Date('2026-12-01'),
        returnDate: new Date('2027-01-15'),
        daysOfTravel: 45,
        applicationType: 'Individual',
        travelerFirstName: 'Kevin',
        travelerSurname: 'Lim',
        birthdate: new Date('1990-06-25'),
        email: 'kevin.lim@example.com',
        mobileNumber: '+639204445566',
        planVariant: 'Multi_Trip_180',
        cruiseCoverage: true,
        hazardousSportsCoverage: false,
        isSchengenDestination: false,
        premium: '5800.00',
        dateReceived: new Date('2026-09-08'),
        status: 'Cancelled',
      },
    ],
  });

  console.log(`Seeded role "${role.name}", branch "${branch.city}", and admin user ${admin.email}.`);
  console.log('Seed complete');
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
